"""added verify_sent_at field

Revision ID: 0b4afa9079dc
Revises: 3cb49aa8b51e
Create Date: 2026-01-18 10:51:07.187007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4afa9079dc'
down_revision: Union[str, Sequence[str], None] = '3cb49aa8b51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verify_sent_at')
    # ### end Alembic commands ###
