"""added last_active_at for users

Revision ID: 37fb6164ad7b
Revises: 6c3a6c401e57
Create Date: 2026-04-30 13:02:46.465236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fb6164ad7b'
down_revision: Union[str, Sequence[str], None] = '6c3a6c401e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_read_cursors_user_id'), table_name='conversation_read_cursors')
    op.drop_index(op.f('ix_messages_conversation_id_seq'), table_name='messages')
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    op.create_index(op.f('ix_messages_conversation_id_seq'), 'messages', ['conversation_id', 'seq'], unique=True)
    op.create_index(op.f('ix_conversation_read_cursors_user_id'), 'conversation_read_cursors', ['user_id'], unique=False)
    # ### end Alembic commands ###
