"""added verify_code field

Revision ID: 3cb49aa8b51e
Revises: f43148259210
Create Date: 2026-01-18 10:41:26.019065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb49aa8b51e'
down_revision: Union[str, Sequence[str], None] = 'f43148259210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verify_code')
    # ### end Alembic commands ###
