"""added bio column for users

Revision ID: 4c0b77674204
Revises: 2f1b7b3f0c2e
Create Date: 2026-02-24 10:03:04.777052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0b77674204'
down_revision: Union[str, Sequence[str], None] = '2f1b7b3f0c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_user_relation'), table_name='relationships')
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.create_index(op.f('ix_relationships_user_relation'), 'relationships', ['user_id', 'relation'], unique=False)
    # ### end Alembic commands ###
