"""added a direct pair key to conversations

Revision ID: 6937728dbb8b
Revises: c5f153987361
Create Date: 2026-02-28 13:47:09.414906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6937728dbb8b'
down_revision: Union[str, Sequence[str], None] = 'c5f153987361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('direct_pair', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'conversations', ['direct_pair'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='unique')
    op.drop_column('conversations', 'direct_pair')
    # ### end Alembic commands ###
