"""added email changing fields

Revision ID: f43148259210
Revises: d6fb1c8c33ee
Create Date: 2026-01-17 12:52:45.646975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43148259210'
down_revision: Union[str, Sequence[str], None] = 'd6fb1c8c33ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_change_code', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email_change_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_change_sent_at')
    op.drop_column('users', 'email_change_code')
    # ### end Alembic commands ###
